spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1090394081080-rloo18gkffem52kmblbbjjcoqofoiprf.apps.googleusercontent.com
            clientSecret: MZh_hQFMs4FAU8hI6qfL5GPo
#            redirectUri: postmessage
#            redirect-url: postmessage
#            redirect-uri: postmessage
#            RedirectUrl: postmessage
#            RedirectUri: postmessage
#          github:
#            clientId: 83ac771b917ee23db7f6
#            clientSecret: ff18a14a8fd914ce6d9a021befaf8a2002f2a46c
#          facebook:
#            clientId: 2651104775149353
#            clientSecret: bdcfb2d46bc1e800bc81865df386451e
#            accessTokenUri: https://graph.facebook.com/oauth/access_token
#            userAuthorizationUri: https://www.facebook.com/dialog/oauth
#            tokenName: oauth_token
#            authenticationScheme: query
#            clientAuthenticationScheme: form
#            resource:
#              userInfoUri: https://graph.facebook.com/me

server:
  port: 8081